### ISSUE TITLE
Getting an album by album ID

### ISSUE THREAD

**Issue by Misofist** [rmp135/imgur#1]
Hi,

I'm trying to use this library to get a list of images from an album ID.

From the docs I can see [Gallery.album()](https://rmp135.github.io/imgur/api/gallery/#album) which appears to use [GET https://api.imgur.com/3/gallery/album/{{galleryHash}}](https://apidocs.imgur.com/#f64e44be-8bf3-47bb-90d5-d1bf39c5e417) and I can see [Account.album()](https://rmp135.github.io/imgur/api/account/#album) which appears to use [GET https://api.imgur.com/3/account/{{username}}/album/{{albumHash}}](https://apidocs.imgur.com/#f57e9ff3-0d25-4804-bc53-53e9e54be813).

But I can't find any way to get an album that's not in the Gallery by its ID. The Imgur API has a method for this, [GET https://api.imgur.com/3/album/{{albumHash}}](https://apidocs.imgur.com/#5369b915-ad8b-47b1-b44b-8e2561e41cee). Am I missing something, or is this feature absent?

Thanks!

**Comment by rmp135** [comment]
You should be able to use Account.album. The Imgur documentation states that it functions the same way as the Album endpoint.

I have noticed the imgur api documentation has been updated since I made this, I'll go back over and fill in any gaps.

**Comment by rmp135** [comment]
May have taken over a year but I finally got around to it. All album endpoints are available in version 0.5.0.
