### ISSUE TITLE
Please close your security vulnerabilities

### ISSUE THREAD

**Issue by rlnt** [rmp135/imgur#6]
Please merge your PRs because your are using `axios` as dependency and it has 2 vulnerabilities.

**Comment by rmp135** [comment]
GitHub tends to be overly cautious with security vulnerabilities, typically they're caused by user provided URLs which isn't possible in server apps such as this one. 

Thanks though, I'll go through and do a big dependency update.

**Comment by rlnt** [comment]
npm itself reports these security issue when installing the package.
Thank you!

**Comment by rlnt** [comment]
When will you do this?

**Comment by rmp135** [comment]
I've just pushed version 0.6.0.
